# - Configuration file stored 2024-11-28 16:28:24.693820 - 
LaserConfig: #!!python/object:controller.LaserConfig
 epos_dll: "@Path:<C:/Users/samue/git/PySacherECLControl/src/SacherECLControl/libs/SacherLib/PythonMotorControlClass/EposCmd64.dll>" # epos_dll: None
 motor_control_pyd: "@Path:<C:/Users/samue/git/PySacherECLControl/src/SacherECLControl/libs/SacherLib/PythonMotorControlClass/lib/Python312/SacherMotorControl.pyd>" # motor_control_pyd: None
 wl_sweep_start: 845 # wl_sweep_start: None
 wl_sweep_stop: 855 # wl_sweep_stop: None
 velocity: 1.6540566248074888 # velocity: None
 acceleration: 1.9904737652227005 # acceleration: None
 deceleration: 1.9904737652227005 # deceleration: None
 available_ports: ['USB0', 'USB1', 'USB2', 'USB3', 'USB4', 'USB5', 'USB6', 'USB7', 'USB8', 'USB9'] # available_ports: None
 port: "USB0" # port: None
